sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "NhVgrtGhy8JnBSJEck88ZWeuq5lyo1aRjyjHTGOGOPSqVTtXZHRuqNbemYmlzHlr24ObK3WLRp2TabISrIhZcRJNbEaWB+qpvm2wnZZ8+DNbzthxIXF+JoVOoJ7zJX7y074hTQOy12T+BjU9aM6ue0UZjmXwjVVRlCeN6WNYZ/HjXs2TjLLwr6cGw3jNG4tRMGZj7HBUt0hD0W0KfFwEj7a8u/uJ3DQojVynA8v05+oRGYWwl9y9YKkiTSM4W/TJeTiRyFCGtuPvKTcfPp6JGWhqtcgFhtun1sOnuMDfkv+0rleGcZz/bt3I7F6kb0D503qRwrVr96e6hFddYTqQ9BbMS1sKsaIaTrWP7dUCjrZW+BVgAUbnK4EdlXz1lU+nHiq1H/2iTJC5JaeW92HUOOlbmUEIqAlevk2EFNrNsCw+n1LAnrZMLPt5f9KX+yVecn9JmRANoyyOVqGgS/1VZQ3Eex+jgPZvt+YGKs6B/ppzhOGWhc+Ew8HrzDpU/fWLbpOgtHjMNua0PygXo6HznhJcZzD7Thbpc+7IRQgY0ffIhLYzER8/LJAlhYUzsU9e5GCRd2WTg84Vs1d3PfJsHq7fX0AxSGpiJQJzzpnUfzxygt9luydEEsZz0JP7rp/cHr1rdDS1I+LuRlLkv8ta6r+EJ5W83IxtfaJhK9BFOkg="
branches:
  only:
    - master
