sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
  - master
env:
  global:
    secure: X/vDg/NyZSKtA/qatNBoRWlg0F4V+oPyNkA3xSR2uxAWvIRQoOttmTYQMx7muothsBgQIK5WB5AJuVnFLJB9E5XHJeyzpdUnZZkVwLtr3pBWvZnVUpUfnxCN8pTE6jTkj+E+9L8jnx9U9dvZ/oHuvd2JT3FHHNzXmDa66O+3rtkaKjCxjxG2LLV/CEaWr1iJikB6OMYoGG9uBxOukMavLb9DbqUbJtANPv2WOIohcOLyb4HoFjDrbPvpdsf8GMU7eCZXqTOmS0+O2uXZMSf/gNdN+piQlZPLhGFkKmYNtWnJZmQdjIZ1ManolnKUM+5cmatTBoKzn5u/F30z16rq6uTvCsZDpGEf3hMr+Smix3JdZm7/tj/U+ffUoURw3JVybjNlZqKhW+8YRUSOBaBuXEZyHiD2oshCADxM5ri/DItnYIeVK44w3cA9rPIk5OsAaErkHLIUaeHkNeGbCGxeOb4zrvfn8aWZ3FvbzElxxkwks4ZJoJ5iIyBBN+HnaeThwGgOW1JAZvsj+zScCWTO8QBVt2+NcdcF20JFpQmG+KHMy5pn8E4HMLaX2Ha5/nroCV/838P1eEFMR3oEdfI48Z+EqUS8wqEwqW/jRveNiQ3hsu0XM9STRqPqsTpG5/ajk4+aTycuVZRSZgkjMif1kSfLjC0IAbR5ZqC1Dv7eXn8=
